# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PhotoRant, a Botzilla Blog
email: bjorke@botzilla.com
description: >- # this means to ignore newlines until "baseurl:"
  You're now viewing the 2018 redesign of PhotoRant.
  As usual topics here include photography, art history, Contax, Leica,
  Fujifilm and Canon, Deep Learning, 3D Game Design, Computer Graphics,
  and a variety of pet conspiracy theories (is there another kind?).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.botzilla.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bjorke
github_username:  joker-b
logo: /assets/botz_dag.jpg
# logo: /images/botzilla-fix-me.jpg
read_time: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
pagination: 4
paginate_path: /page:num/
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
copyright: "All site content ©1997-2018 by Kevin Bjorke"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
