# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-theme-so-simple
title: "PhotoRant: There Are Many Kinds of Pictures"
email: bjorke@botzilla.com
# description: >- # this means to ignore newlines until "baseurl:"
#  A newer, lighter, PhotoRant.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.botzilla.com" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: bjorke
github_username:  joker-b
logo: /assets/botz_dag.jpg
# logo: /images/botzilla-fix-me.jpg
read_time: true
excerpt_separator: <!--more-->

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-4450500-3" # Google Analytics id, e.g. "UA-NNNNNNNN-N"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
# paginate: 5
# pagination: 5
# paginate_path: /page:num/
search_full_content: false

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
copyright: "All site content ©1997-2023 by <a href=\"https://www.botzilla.com/about.html\">Kevin Bjorke</a>"
ss_copyright: "All artworks ©2012-2023 See See Lo."

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll/tagging
  - jekyll-tagging-related_posts

#   - jekyll-paginate

# Collections
collections:
  liquiditysf:
    output: true
    permalink: /:collection/:path/
  paintings:
    output: true
    permalink: /:collection/:path/
  boxes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# commenting
disqus:
    shortname: botzilla

# Site Author
author:
  name: Kevin Bjorke 
  picture: /assets/botz_dag.jpg
  email:
  twitter: bjorke
  links:
    - title: Twitter
      url: https://twitter.com/bjorke
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/kevin_bjorke
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/joker-b
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/bjorke
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/kevin_bjorke
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/joker-b
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

ss_footer_links:
  - title: Instagram
    url: https://instagram.com/seeseeloca
    icon: fab fa-instagram

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _retired/
  - _dotfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

