name: Build and Zip Jekyll Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Set up Ruby and install Bundler
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true  # Automatically bundle install and cache

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Compress _site directory
        run: tar -czf botzo.tar.gz -C _site .

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: botzo.tar.gz
          path: botzo.tar.gz

      - name: Send zip to Botzilla
        env:
	   SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
	   SSH_PORT: ${{ secrets.SSH_PORT }}
	   SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
	   SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
	    mkdir -p ~/.ssh
	    echo "${SSH_KEY}" > ~/.ssh/id_rsa
	    chmod 600 ~/.ssh/id_rsa
	    scp -P ${SSH_PORT} -o StrictHostKeyChecking=no botzo.tar.gz ${SSH_USERNAME}@${SSH}:html/botzo.tar.gz
        shell: bash


